### ISSUE TITLE
Getting a release for snomed-scg-parser

### ISSUE THREAD

**Issue by SamithaS** [IHTSDO/snomed-scg-parser#1]
Would it be possible to get a release for this project. Still this is not available in maven central repo.

**Comment by CoderMChu** [comment]
snomed-scg-parser 1.0.0 is now released and ready in our maven repo.

**Comment by rorydavidson** [comment]
@CoderMChu could we please add that released package to the releases on this repo in GitHub?

**Comment by CoderMChu** [comment]
Please find the release package via the link below:
https://maven.ihtsdotools.org/service/local/repositories/releases/content/org/snomed/languages/snomed-scg-parser/1.0.0/snomed-scg-parser-1.0.0.jar

**Comment by kaicode** [comment]
Artifacts from the Snomed International / IHTSDO maven repository can be access by adding the following to your pom.xml:
```
<repositories>
	<repository>
		<id>ihtsdo-releases</id>
		<id>IHTSDO Releases</id>
		<url>https://maven.ihtsdotools.org/content/repositories/releases</url>
		<snapshots>
			<enabled>false</enabled>
		</snapshots>
	</repository>
</repositories>
```

**Comment by SamithaS** [comment]
Thanks @kaicode
