### ISSUE TITLE
 SNOMED CT Identifier( SCTID) check-digit validation

### ISSUE THREAD

**Issue by SamithaS** [IHTSDO/snomed-scg-parser#2]
Is there a support or future plan to introduce  SNOMED CT Identifier( SCTID) check-digit validation with this library?

**Comment by kaicode** [comment]
Hi @SamithaS, there is no support and no current plan to develop support for Verhoeff check digit validation. This could be achieved using apache commons VerhoeffCheckDigit class as demonstrated here - https://github.com/IHTSDO/snomed-utilities/blob/6931f84/src/main/java/org/ihtsdo/snomed/util/SnomedUtils.java#L15
We welcome pull requests!
Thanks, Kai

**Comment by SamithaS** [comment]
Thanks @kaicode
