### ISSUE TITLE
g4 file is missing

### ISSUE THREAD

**Issue by gayanper** [IHTSDO/snomed-scg-parser#3]
Where can we find the .g4 file if we want to alter the parser or improve the parser ?

**Comment by kaicode** [comment]
@CoderMChu do you still have the SCG.txt file you used to generate the parser with ANTLR?
If you have the file please add it to the repo in a folder called "parser-generation" to match the snomed-ecl-parser project.

**Comment by CoderMChu** [comment]
Please find the SCG.txt file in the parser-generation folder.
